M: discord.com: Use empty response instead of error
easylist/easylist pull request #14223
Opened 2022-11-24 09:28 UTC by Alcaro

Discord keeps the science around until the /science request succeeds. Pretend it works, it's a memory leak.

This change has no effect in Firefox, due to https://github.com/uBlockOrigin/uBlock-issues/issues/2381. However, it works in Chrome.

2022-11-24 10:03 UTC, krystian3w requested changes
Invalid syntax, list allow only:

https://help.eyeo.com/adblockplus/how-to-write-filters#rewrite


> `$rewrite=abp-resource:`

> -   `blank-text`  - empty text
> -   `blank-css`  - empty stylesheet
> -   `blank-js`  - empty JavaScript
> -   `blank-html`  - empty HTML document
> -   `blank-mp3`  - a 0.1s silent MP3 audio file
> -   `1x1-transparent-gif`  - 1x1 pixel transparent GIF image
> -   `2x2-transparent-png`  - 2x2 pixels transparent PNG image
> -   `3x2-transparent-png`  - 3x2 pixels transparent PNG image
> -   `32x32-transparent-png`  - 32x32 pixels transparent PNG image

2022-11-24 10:09 UTC, Alcaro commented
Oh right, $empty is uBlock Origin only.

Sure, can do.

2022-11-24 10:12 UTC, krystian3w commented
>Oh right, $empty is uBlock Origin only.

Origin copied from AdGuard.

2022-11-24 10:13 UTC, krystian3w approved these changes
<!-- -->

2022-11-24 12:15 UTC, krystian3w commented
however: The ABP/AdBlock add-on parser, does not pass without a domain or 'TLD' - at end of file needed is:

`,domain=discord.com`

or after `$` as `domain=discord.com,`

---

For uBO maybe better open another PR: https://github.com/uBlockOrigin/uBlock-issues/issues/857#issuecomment-741768956 if accept this no change support list: https://github.com/gorhill/uBlock/commit/0b5f53923fc4fd7e6927ce57cd9226a61bcbdb88

The status of automatic translation in AdGuard is unknown to me.

2022-11-24 12:26 UTC, Alcaro commented
Add domain rule, sure, works for me.

uBO's syntax highlighter recognizes rewrite=abp-resource:blank-js as valid, but not blank-text, so I'll switch to that. Discord itself doesn't care what the response is, as long as it's not a network failure.

Fixing for uBO only feels contrary to the spirit of open source to me; Discord's memory leak exists under all ad blockers, better fix it upstream.

2022-11-24 12:36 UTC, krystian3w approved these changes

2022-11-25 00:49 UTC, ryanbr commented
Won't add into EL

2022-11-25 00:49 UTC, closed without merging

2022-11-25 07:46 UTC, krystian3w commented
Sic!