Add new google ads carousel match format.
easylist/easylist pull request #6124
Opened 2020-10-09 09:16 UTC by jameshilliard

2020-10-09 11:29 UTC, krystian3w requested changes

2020-10-09 11:29 UTC, krystian3w commented on easylist/easylist_general_hide.txt
> +###atvcap > div:has(h3[role="heading"] > span:has-text(/^Ads/))
- `:has-text(foo)` and `:has(foo)` is no supported by ABP/AdBlock

- omitted domains is no supported by ABP/AdBlock for procedural filters (like `:-abp-has(foo)`)

   - also no supported simplify procedural filters to only TLD like `com##...`

2020-10-09 11:37 UTC, krystian3w commented
Filter need move to other file, if no possible remove useage `:-abp-has()` and `:-abp-contains()`

It would also be appropriate to add around ~220 google domains with their various public suffixes ("TLD") before `#?#`.

2020-10-09 12:02 UTC, krystian3w requested changes
<!-- -->

2020-10-10 16:52 UTC, jameshilliard commented
Think it's safe to unconditionally block `#atvcap`?

2020-10-11 08:58 UTC, ryanbr commented
We already have `###atvcap + #tvcap > .mnr-c > .commercial-unit-mobile-top` (which #atvcap would overrule.) How safe is blocking #atvcap outright?

2020-10-11 20:52 UTC, jameshilliard commented
> How safe is blocking #atvcap outright?

Well the class name sounds to me like it's ad specific and not a random div name, but hard to say for sure.

2021-11-02 00:18 UTC, closed without merging